imagePullPolicy: IfNotPresent

nodeSelector: {}

bootnode:
  image:
    repository: ethereum/client-go
    tag: alltools-v1.7.3

ethstats:
  image:
    repository: ethereumex/eth-stats-dashboard
    tag: v0.0.1
  webSocketSecret: my-secret-for-connecting-to-ethstats
  service:
    type: LoadBalancer

geth:
  image:
    repository: ethereum/client-go
    tag: v1.7.3
  replicaCount: 2
  service:
    type: ClusterIP
  args:
    rpcapi: 'eth,net,web3'
  genesis:
    difficulty: '0x0400'
    gasLimit: '0x8000000'
    networkId: 1
  account:
    address:
    privateKey:
    secret:
