name: Run integration tests
on: [push]
jobs:
  integration-tests:
    timeout-minutes: 40
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up linux environment
        run: # installs development tools and updates .bash_profile
          bash test/integration/setup-linux-environment.sh
      - name: Setup integration test environment
        run: |
          source $HOME/.bash_profile
          bash test/integration/start-integration-env.sh
      - name: Execute integration tests
        run: |
          source $HOME/.bash_profile
          . test/integration/vagrantenv.sh
          export LOG_LEVEL=DEBUG
          python3 -m pytest -olog_cli=false -olog_level=DEBUG -olog_file=vagrant/data/pytest.log -v $i

          # some destructive tests are marked with pytest.mark.individual_file and they have
          # to be run individually
          # (and might modify test/integration/vagrantenv.sh)
          for i in src/py/test_*
          do
            python3 -m pytest -m individual_file -olog_cli=false -olog_level=DEBUG -olog_file=vagrant/data/pytest.log -v $i
            . test/integration/vagrantenv.sh
          done
