name: Run integration tests
on: [push]
jobs:
  integration-tests:
    timeout-minutes: 40
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up linux environment
        run: # installs development tools and updates .bash_profile
          bash test/integration/setup-linux-environment.sh
      - name: Setup integration test environment
        run: |
          source $HOME/.bash_profile
          bash test/integration/start-integration-env.sh
      - name: Execute any chain integration tests
        run: |
          source $HOME/.bash_profile
          . test/integration/vagrantenv.sh
          export LOG_LEVEL=DEBUG
          bash test/integration/execute_integration_tests_against_any_chain.sh
      - name: Execute test chain integration tests
        run: |
          source $HOME/.bash_profile
          . test/integration/vagrantenv.sh
          export LOG_LEVEL=DEBUG
          bash test/integration/execute_integration_tests_against_test_chain.sh
          python3 -m pytest -olog_level=$loglevel -v -olog_file=vagrant/data/pytest.log -v \
            ${TEST_INTEGRATION_PY_DIR}/destructive_test_no_whitelisted_validators.py
