name: Build then Deploy to Pinata

on: 
  push:
    paths: 
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14.x'

      - name: Build App
        env:
          VUE_APP_DEPLOYMENT_TAG: "sandpit"
          VUE_APP_ETHEREUM_ASSET_TAG: "ethereum.ropsten"
          VUE_APP_SIFCHAIN_ASSET_TAG: "sifchain.sandpit"
        run: yarn install --frozen-lockfile && yarn core:build && yarn app:build

      - name: Deploy App to IPFS/Pinata
        id: pinata
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4
        with:
          pin-name: 'Sifchain ${{ github.sha }}'
          path: './ui/app/dist'
          pinata-api-key: ${{ secrets.PINATA_API_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_SECRET_KEY }}
          verbose: true
          remove-old: true
      
      - name: Write Code Comment
        uses: thollander/actions-comment-pull-request@master
        with:
          message: ${{steps.pinata.outputs.hash}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# https://github.com/marketplace/actions/cloudflare-dns