name: Pull Request Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - feature/add-slither-to-ci

jobs:
  slither:
    name: slither
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          sudo apt-get install gcc libpq-dev -y
          sudo apt-get install python-dev  python-pip -y
          sudo apt-get install python3-dev python3-pip python3-setuptools python3-venv python3-wheel -y
          pip3 install wheel

      - name: Run Slither
        run: |
          cd ./smart-contracts
          make slither
